package com.bank.model.Accounts;

import com.bank.exceptions.InsufficientFundsException;
import com.bank.exceptions.InvalidAmountException;
import com.bank.model.Customers.Customer;
import com.bank.utils.FormatUtils;

public class SavingsAccount extends Account {

    private double interestRate;
    private double minimumBalance;

    public SavingsAccount(double deposit, Customer customer){
        super(deposit, customer);
        this.interestRate = 0.035f;
        this.minimumBalance = 500;
    }

    /**
     *
     * this constructor is for retrieving accounts from the file persistent storage, it is not for creating new accounts
     * @param accountNumber accountNumber already available not autogenerated
     * @param customer
     * @param balance
     * @param status
     */
    public SavingsAccount(String accountNumber, Customer customer, double balance, String status) {
        super(accountNumber, customer, balance, status);
        this.interestRate = 0.035f;
        this.minimumBalance = 500;
    }

    @Override
    public String getAccountType() {
        return "Savings";
    }

    @Override
    public void displayAccountDetails() {


        String accountNumber = FormatUtils.giveStringFixedLength(super.getAccountNumber(), 10).toUpperCase();
        String customerName = FormatUtils.giveStringFixedLength(super.getCustomer().getName(), 20);
        String type = FormatUtils.giveStringFixedLength(getAccountType(), 12);
        String balance = FormatUtils.giveStringFixedLength(String.valueOf(FormatUtils.formatAmount(super.getBalance()) ) , 11);
        String status = FormatUtils.giveStringFixedLength(super.getStatus(), 10);
        String formatted = String.format("%s | %s | %s | $%s | %s", accountNumber, customerName, type,balance, status
        );
        System.out.println(formatted);
        String spaces = " ".repeat(10) ;
        String minBalance = "Min Balance: $" + FormatUtils.formatAmount( this.getMinimumBalance());
        String interestRate = "Interest Rate: " + String.format("%.1f",getInterestRate()*100) + "%" ;

        String formatted1 = String.format("%s | %s | %s", spaces, interestRate, minBalance);
        System.out.println(formatted1);

    }

    @Override
    public void deposit(double amount)  {
        double newBalance = calculateDeposit(amount);
        super.setBalance(newBalance);
    }

    @Override
    public void withdraw(double amount) {
        double balance = calculateWithdrawal(amount);
        super.setBalance(balance);

    }

    @Override
    public double calculateDeposit(double amount) {
        if (amount <= 0){
            throw new InvalidAmountException("amount should be greater than 0");
        }
        return super.getBalance() +amount;
    }

    @Override
    public double calculateWithdrawal(double amount)   {
        double balance = super.getBalance();
        if (amount <= 0 ){
            String message = "Error: Invalid amount. Amount must be greater than 0";
            throw new InvalidAmountException(message);
        }
        double remainingBalance =  balance - amount;

        if (remainingBalance < this.minimumBalance){

            String message = "This is a saving account The minimum balance is $500\n"+ "you can only  withdraw up to $ "+ FormatUtils.formatAmount(balance-this.getMinimumBalance());
            throw new InsufficientFundsException(message);
        }
        return remainingBalance;
    }


    public double calculateInterest(){
        double balance = super.getBalance();
        double interestEarned = Math.round(this.interestRate*balance);


        super.setBalance(balance + interestEarned);
        return interestEarned;
    }

    public double getInterestRate() {
        return interestRate;
    }

    public void setInterestRate(double interestRate) {
        this.interestRate = interestRate;
    }

    public double getMinimumBalance() {
        return minimumBalance;
    }

    public void setMinimumBalance(double minimumBalance) {
        this.minimumBalance = minimumBalance;
    }

    @Override
    public boolean processTransaction(double amount, String type)  {
        if (type.equalsIgnoreCase("withdraw")){
            withdraw(amount);
            return true;
        }
        if (type.equalsIgnoreCase("deposit")){
            deposit(amount);
            return true;
        }
        return false;
    }
}
